#!/bin/bash
# Exit immediately if a command exits with a non-zero status.
set -e
# Print commands and their arguments as they are executed.
set -x

# Redirect all output to a log file and to the console for easier debugging.
exec > >(sudo tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1

echo "--- Starting UserData script execution... $(date) ---"

# --- Resilient Package Installation ---
for i in {1..3}; do
    echo "Attempt $i to install packages..."
    sudo dnf update -y && sudo dnf install -y httpd ruby wget && break
    echo "dnf command failed. Retrying in 20 seconds..."
    sleep 20
done

# --- Web Server Setup ---
echo "Starting and enabling httpd..."
sudo systemctl start httpd
sudo systemctl enable httpd

# Create web root and set permissions proactively
sudo mkdir -p /var/www/html
sudo chown -R apache:apache /var/www/html
sudo chmod -R 755 /var/www/html

# --- Configure Apache Port and Restart ---
echo "Configuring httpd to listen on port 8080..."
sudo sed -i 's/^Listen 80$/Listen 8080/' /etc/httpd/conf/httpd.conf # Use anchors for precise replacement

# Add a VirtualHost block to explicitly serve content on port 8080
echo "Configuring Apache VirtualHost for port 8080..."
cat <<APACHE_CONF | sudo tee /etc/httpd/conf.d/application_port.conf
<VirtualHost *:8080>
    DocumentRoot /var/www/html
    <Directory /var/www/html>
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
    </Directory>
    ErrorLog /var/log/httpd/application_error_log
    CustomLog /var/log/httpd/application_access_log combined
</VirtualHost>
APACHE_CONF

sudo systemctl restart httpd

# --- Wait for Apache to be ready (for health checks) ---
echo "Waiting for Apache to listen on 8080 and respond to /healthz..."
MAX_RETRIES=10
RETRY_INTERVAL=10
for i in $(seq 1 $MAX_RETRIES); do
    if sudo ss -tulnp | grep -q ":8080"; then
        echo "Apache is listening on port 8080. Testing /healthz..."
        if curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/healthz | grep -q "200"; then
            echo "/healthz endpoint responding with 200 OK."
            break
        else
            echo "/healthz endpoint not yet 200 OK. Retrying in $RETRY_INTERVAL seconds..."
        fi
    else
        echo "Apache not yet listening on 8080. Retrying in $RETRY_INTERVAL seconds..."
    fi
    sleep $RETRY_INTERVAL
    if [ $i -eq $MAX_RETRIES ]; then
        echo "Reached max retries. Apache might not be fully ready. Exiting with error."
        exit 1 # Exit with error so ASG marks instance as unhealthy and terminates
    fi
done

# --- Create Health Check file ---
echo "Creating healthz file..."
echo "OK" | sudo tee /var/www/html/healthz

# --- Fetch EC2 Instance Metadata via IMDSv2 (server-side) ---
echo "Fetching EC2 instance metadata via IMDSv2..."
# Request a token first
IMDS_TOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600" || echo "")

INSTANCE_ID="N/A (IMDS Error)"
INSTANCE_AZ="N/A (IMDS Error)"
INSTANCE_NAME_DISPLAY="N/A (IMDS Error)"

if [ -z "$IMDS_TOKEN" ]; then
    echo "WARNING: Failed to get IMDSv2 token. Instance details will be N/A."
else
    # Fetch metadata using the token, with fallback values if curl fails
    INSTANCE_ID=$(curl -s -H "X-aws-ec2-metadata-token: $IMDS_TOKEN" http://169.254.169.254/latest/meta-data/instance-id || echo "N/A (IMDS Error)")
    INSTANCE_AZ=$(curl -s -H "X-aws-ec2-metadata-token: $IMDS_TOKEN" http://169.254.169.254/latest/meta-data/placement/availability-zone || echo "N/A (IMDS Error)")
    INSTANCE_HOSTNAME=$(curl -s -H "X-aws-ec2-metadata-token: $IMDS_TOKEN" http://169.254.169.254/latest/meta-data/hostname || echo "N/A (IMDS Error)")
    INSTANCE_NAME_DISPLAY="${INSTANCE_HOSTNAME%%.*}" # Extract part before first dot
fi

echo "EC2_INSTANCE_ID=$INSTANCE_ID"
echo "EC2_INSTANCE_AZ=$INSTANCE_AZ"
echo "EC2_INSTANCE_NAME_DISPLAY=$INSTANCE_NAME_DISPLAY"

# --- Create JavaScript file with instance info ---
echo "Creating instance_info.js with fetched details..."
cat <<JS_FILE | sudo tee /var/www/html/instance_info.js
// This file is generated by user-data script during instance bootstrap
// It contains instance metadata fetched from IMDSv2.
const INSTANCE_DETAILS = {
    id: "${INSTANCE_ID}",
    name: "${INSTANCE_NAME_DISPLAY}",
    az: "${INSTANCE_AZ}"
};
JS_FILE

sudo chown apache:apache /var/www/html/instance_info.js # Ensure ownership

# --- CodeDeploy Agent Installation ---
echo "Downloading CodeDeploy agent installer..."
CODEDEPLOY_AGENT_INSTALLER_URL="https://aws-codedeploy-us-east-1.s3.us-east-1.amazonaws.com/latest/install"
sudo wget "$CODEDEPLOY_AGENT_INSTALLER_URL" -O /tmp/install

echo "Making installer executable and running..."
sudo chmod +x /tmp/install
sudo /tmp/install auto

# --- Verify CodeDeploy Agent ---
echo "Checking CodeDeploy agent status..."
sleep 10
sudo systemctl status codedeploy-agent || echo "CodeDeploy agent status check failed, but continuing..."

echo "--- Finished UserData script execution. $(date) ---"