version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      python: 3.11
    commands:
      - echo "Installing AWS CDK..."
      - npm install -g aws-cdk
      - echo "Installing Python dependencies..."
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Synthesizing the CDK app..."
      - cdk synth MyMainInfrastructureStack --output cdk.out
      - echo "Renaming latest template to main-template.json..."
      - LATEST_TEMPLATE=$(find cdk.out -type f -name "*.template.json" | head -n 1)
      - cp "$LATEST_TEMPLATE" cdk.out/main-template.json
artifacts:
  secondary-artifacts:
    CdkTemplatesOutput:
      base-directory: cdk.out
      files:
        - '**/*'
    AppBundleOutput:                
      base-directory: .            
      files:
        - '**/*'
