version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing CDK globally"
      - npm install -g aws-cdk

  pre_build:
    commands:
      - echo "Starting CDK infrastructure deployment for stack: ${CDK_INFRA_STACK_NAME}"

  build:
    commands:
      - echo "Running cdk deploy for infrastructure stack: ${CDK_INFRA_STACK_NAME}..."
      - cdk deploy "${CDK_INFRA_STACK_NAME}" --require-approval never --outputs-file cdk-deploy-outputs.json
      - echo "CDK infrastructure deployment complete."

artifacts:
  files:
    - cdk-deploy-outputs.json

cache:
  paths:
    - '/root/.npm/**/*'



    
