version: 0.0
os: linux
files:
  - source: webapp/index.html
    destination: /var/www/html/
  - source: webapp/scripts/
    destination: /tmp/codedeploy/scripts/

permissions:
  - object: /tmp/codedeploy/scripts/
    pattern: "**"
    owner: root
    group: root
    mode: 755

hooks:
  ApplicationStop:
    - location: webapp/scripts/stop_server.sh
      timeout: 60
      runas: root
  BeforeInstall:
    - location: webapp/scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: webapp/scripts/start_server.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: webapp/scripts/validate_service.sh
      timeout: 300
      runas: root
